loki:
  auth_enabled: false
  limits_config:
    allow_structured_metadata: true
    ingestion_rate_mb: 10000
    ingestion_burst_size_mb: 1000
    per_stream_rate_limit: 512M
    per_stream_rate_limit_burst: 1024M
  ingester:
    chunk_encoding: snappy
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  tracing:
    enabled: true
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 4

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::507326814593:role/ecomm_iam_role

deploymentMode: SimpleScalable

backend:
  replicas: 3
  persistence:
    storageClass: gp2
  affinity: {}
read:
  replicas: 3
  affinity: {}
write:
  replicas: 3
  persistence:
    storageClass: gp2
  affinity: {}

# Enable minio for storage
minio:
  enabled: true
  persistence:
    enabled: true
    storageClass: "gp2"
    size: 10Gi

# Zero out replica counts of other deployment modes
singleBinary:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

lokiCanary:
  enabled: false
test:
  enabled: false