apiVersion: v2
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool for Kubernetes.
name: argo-cd
version: 7.3.4
home: https://github.com/argoproj/argo-helm
dependencies:
  - name: argo-cd
    version: 7.3.4
    repository: https://argoproj.github.io/argo-helm/