apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "carts-service.fullname" . }}-configmap
data:
  sqs_queue_url_ordering_to_carts: "https://sqs.us-west-2.amazonaws.com/507326814593/ordering-to-carts"
  sqs_vpc_endpoint_url: "https://sqs.us-west-2.amazonaws.com"
  otel_collector_endpoint: "http://ecomm-opentelemetry-collector.observability.svc.cluster.local:4318"