apiVersion: v2
description: A Helm chart for Prometheus.
name: prometheus
version: 25.27.0
home: https://github.com/prometheus-operator/kube-prometheus
dependencies:
  - name: prometheus
    version: 25.27.0
    repository: https://prometheus-community.github.io/helm-charts